export const SHORTCUTS = {
  TAB_CLOSE: 'Ctrl+W',
  TAB_NEXT: 'Ctrl+Tab',
  TAB_PREVIOUS: 'Ctrl+Shift+Tab',
  TAB_SEARCH: 'Ctrl+Shift+A',

  REQUEST_SAVE: 'Ctrl+S',
  REQUEST_SEND: 'Ctrl+Enter',

  ITEM_RENAME: 'Ctrl+E',
  ITEM_DUPLICATE: 'Ctrl+D',
  ITEM_DELETE: 'Delete',
  TOGGLE_SIDEBAR: 'Ctrl+B',

  CLEAR_REQUEST_CONSOLE: 'Ctrl+K',
  TOGGLE_REQUEST_CONSOLE: 'Ctrl+"',
  TOGGLE_CONSOLE: 'F12',
} as const;

export const COMMANDS = {
  TAB_CLOSE: 'tab.close',
  TAB_NEXT: 'tab.next',
  TAB_PREVIOUS: 'tab.previous',
  TAB_SEARCH: 'tab.search',

  REQUEST_SAVE: 'request.save',
  REQUEST_SEND: 'request.send',

  TOGGLE_SIDEBAR: 'sidebar.toggle',
  ITEM_RENAME: 'item.rename',
  ITEM_DUPLICATE: 'item.duplicate',
  ITEM_DELETE: 'item.delete',

  CLEAR_REQUEST_CONSOLE: 'request.console.clear',
  TOGGLE_REQUEST_CONSOLE: 'request.console.toggle',
  TOGGLE_CONSOLE: 'console.toggle',
} as const;

export type Command = (typeof COMMANDS)[keyof typeof COMMANDS];

export const SHORTCUT_TO_COMMAND: Record<string, Command> = {
  [SHORTCUTS.TAB_CLOSE]: COMMANDS.TAB_CLOSE,
  [SHORTCUTS.TAB_NEXT]: COMMANDS.TAB_NEXT,
  [SHORTCUTS.TAB_PREVIOUS]: COMMANDS.TAB_PREVIOUS,
  [SHORTCUTS.TAB_SEARCH]: COMMANDS.TAB_SEARCH,

  [SHORTCUTS.REQUEST_SAVE]: COMMANDS.REQUEST_SAVE,
  [SHORTCUTS.REQUEST_SEND]: COMMANDS.REQUEST_SEND,

  [SHORTCUTS.ITEM_RENAME]: COMMANDS.ITEM_RENAME,
  [SHORTCUTS.ITEM_DUPLICATE]: COMMANDS.ITEM_DUPLICATE,
  [SHORTCUTS.ITEM_DELETE]: COMMANDS.ITEM_DELETE,
  [SHORTCUTS.TOGGLE_SIDEBAR]: COMMANDS.TOGGLE_SIDEBAR,

  [SHORTCUTS.CLEAR_REQUEST_CONSOLE]: COMMANDS.CLEAR_REQUEST_CONSOLE,
  [SHORTCUTS.TOGGLE_REQUEST_CONSOLE]: COMMANDS.TOGGLE_REQUEST_CONSOLE,
  [SHORTCUTS.TOGGLE_CONSOLE]: COMMANDS.TOGGLE_CONSOLE,
};
