export const SHORTCUTS = {
  TAB_CLOSE: 'Ctrl+W',
  TAB_NEXT: 'Ctrl+Tab',
  TAB_PREVIOUS: 'Ctrl+Shift+Tab',
  TAB_SEARCH: 'Ctrl+Shift+A',
  GLOBAL_SEARCH: 'Ctrl+K',

  REQUEST_SEND: 'Ctrl+Enter',

  ITEM_NEXT: 'ArrowDown',
  ITEM_PREVIOUS: 'ArrowUp',
  ITEM_SELECT: 'Enter',
  ITEM_SAVE: 'Ctrl+S',
  ITEM_COLLAPSE: 'ArrowLeft',
  ITEM_EXPAND: 'ArrowRight',
  ITEM_RENAME: 'Ctrl+E',
  ITEM_DUPLICATE: 'Ctrl+D',
  ITEM_DELETE: 'Delete',
  TOGGLE_SIDEBAR: 'Ctrl+B',

  CLEAR_REQUEST_CONSOLE: 'Ctrl+L',
  TOGGLE_REQUEST_CONSOLE: 'Ctrl+"',
  TOGGLE_CONSOLE: 'F12',
} as const;

export const COMMANDS = {
  TAB_CLOSE: 'tab.close',
  TAB_NEXT: 'tab.next',
  TAB_PREVIOUS: 'tab.previous',
  TAB_SEARCH: 'tab.search',
  GLOBAL_SEARCH: 'global.search',

  REQUEST_SEND: 'request.send',

  ITEM_NEXT: 'item.next',
  ITEM_PREVIOUS: 'item.previous',
  ITEM_SELECT: 'item.select',
  ITEM_SAVE: 'item.save',
  ITEM_COLLAPSE: 'item.collapse',
  ITEM_EXPAND: 'item.expand',
  ITEM_RENAME: 'item.rename',
  ITEM_DUPLICATE: 'item.duplicate',
  ITEM_DELETE: 'item.delete',
  TOGGLE_SIDEBAR: 'sidebar.toggle',

  CLEAR_REQUEST_CONSOLE: 'request.console.clear',
  TOGGLE_REQUEST_CONSOLE: 'request.console.toggle',
  TOGGLE_CONSOLE: 'console.toggle',

  ITEM_REQUEST_SAVE_TO_COLLECTION: 'item.request_save_to_collection',
} as const;

export type Command = (typeof COMMANDS)[keyof typeof COMMANDS];

export const SHORTCUT_TO_COMMAND: Record<string, Command> = {
  [SHORTCUTS.TAB_CLOSE]: COMMANDS.TAB_CLOSE,
  [SHORTCUTS.TAB_NEXT]: COMMANDS.TAB_NEXT,
  [SHORTCUTS.TAB_PREVIOUS]: COMMANDS.TAB_PREVIOUS,
  [SHORTCUTS.TAB_SEARCH]: COMMANDS.TAB_SEARCH,
  [SHORTCUTS.GLOBAL_SEARCH]: COMMANDS.GLOBAL_SEARCH,

  [SHORTCUTS.REQUEST_SEND]: COMMANDS.REQUEST_SEND,

  [SHORTCUTS.ITEM_NEXT]: COMMANDS.ITEM_NEXT,
  [SHORTCUTS.ITEM_PREVIOUS]: COMMANDS.ITEM_PREVIOUS,
  [SHORTCUTS.ITEM_SAVE]: COMMANDS.ITEM_SAVE,
  [SHORTCUTS.ITEM_SELECT]: COMMANDS.ITEM_SELECT,
  [SHORTCUTS.ITEM_COLLAPSE]: COMMANDS.ITEM_COLLAPSE,
  [SHORTCUTS.ITEM_EXPAND]: COMMANDS.ITEM_EXPAND,
  [SHORTCUTS.ITEM_RENAME]: COMMANDS.ITEM_RENAME,
  [SHORTCUTS.ITEM_DUPLICATE]: COMMANDS.ITEM_DUPLICATE,
  [SHORTCUTS.ITEM_DELETE]: COMMANDS.ITEM_DELETE,
  [SHORTCUTS.TOGGLE_SIDEBAR]: COMMANDS.TOGGLE_SIDEBAR,

  [SHORTCUTS.CLEAR_REQUEST_CONSOLE]: COMMANDS.CLEAR_REQUEST_CONSOLE,
  [SHORTCUTS.TOGGLE_REQUEST_CONSOLE]: COMMANDS.TOGGLE_REQUEST_CONSOLE,
  [SHORTCUTS.TOGGLE_CONSOLE]: COMMANDS.TOGGLE_CONSOLE,
};
